language: c
os: linux
dist: bionic
compiler:
  - gcc
  - clang
arch:
  - amd64
script: ./runtests.sh

jobs:
  include:
    - os: osx
      compiler: clang
      env:
        - LDFLAGS="-L/usr/local/bin/lib/"
    - stage: coverage
      os: linux
      compiler: gcc
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y lcov
        - sudo apt-get install -y libsodium-dev
        - sudo apt-get install -y lib25519-dev
        - gem install coveralls-lcov
      script: ./runlcov.sh
      after_success:
        - coveralls-lcov ref/xwing.lcov